### ISSUE TITLE
about Cython

### ISSUE THREAD

**Issue by liyuke65535** [MinghuiChen43/CIL-ReID#6]
hello! I got an error before training:
```
(reid) liyuke@song12306:~/CIL-ReID-main$ python train.py
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from processor import do_train
  File "/home/liyuke/CIL-ReID-main/processor/__init__.py", line 1, in <module>
    from .processor import do_train, do_inference
  File "/home/liyuke/CIL-ReID-main/processor/processor.py", line 7, in <module>
    from utils.metrics import R1_mAP_eval
  File "/home/liyuke/CIL-ReID-main/utils/metrics.py", line 5, in <module>
    from .rank_cylib.rank_cy import evaluate_cy
ModuleNotFoundError: No module named 'utils.rank_cylib.rank_cy'
```
instruct:
```
python train.py
```
and my env list:
```
Package                       Version
----------------------------- -----------
absl-py                       1.0.0
albumentations                1.1.0
anaconda-client               1.9.0
astunparse                    1.6.3
attrs                         21.4.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
brotlipy                      0.7.0
cachetools                    4.2.4
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.4
chex                          0.1.0
cloudpickle                   2.0.0
clu                           0.0.6
clyent                        1.2.2
contextlib2                   21.6.0
cryptography                  36.0.0
cycler                        0.11.0
Cython                        0.29.28
debugpy                       1.5.1
decorator                     5.1.0
dill                          0.3.4
dm-tree                       0.1.6
einops                        0.3.2
entrypoints                   0.4
faiss-gpu                     1.7.1.post3
flatbuffers                   2.0
flax                          0.3.6
fonttools                     4.28.5
gast                          0.4.0
google-auth                   2.3.3
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
googleapis-common-protos      1.54.0
grpcio                        1.43.0
h5py                          3.6.0
idna                          3.3
imagecorruptions              1.1.2
imageio                       2.16.2
importlib-metadata            4.11.3
importlib-resources           5.4.0
ipdb                          0.13.9
ipykernel                     6.11.0
ipython                       7.30.0
ipython-genutils              0.2.0
jax                           0.2.26
jaxlib                        0.1.75
jedi                          0.18.1
joblib                        1.1.0
jsonschema                    3.2.0
jupyter-client                7.0.6
jupyter-core                  4.9.2
keras                         2.7.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.2
libclang                      12.0.0
lmdb                          1.3.0
matplotlib                    3.5.1
matplotlib-inline             0.1.3
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
ml-collections                0.1.0
msgpack                       1.0.3
nbformat                      5.1.3
nest-asyncio                  1.5.4
networkx                      2.8
numpy                         1.22.1
olefile                       0.46
opencv-python                 4.5.5.62
opencv-python-headless        4.5.5.64
opt-einsum                    3.3.0
optax                         0.1.0
packaging                     21.3
parso                         0.8.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.2.4
promise                       2.3
prompt-toolkit                3.0.22
protobuf                      3.19.3
psutil                        5.8.0
ptyprocess                    0.7.0
pycparser                     2.21
Pygments                      2.10.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.6
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytorch-ignite                0.1.2
pytz                          2021.3
PyWavelets                    1.3.0
PyYAML                        5.4.1
pyzmq                         19.0.2
qudida                        0.0.4
requests                      2.27.1
requests-oauthlib             1.3.0
rsa                           4.8
scikit-image                  0.19.2
scikit-learn                  1.0.2
scipy                         1.7.3
setuptools                    58.0.4
six                           1.16.0
sklearn                       0.0
tensorboard                   2.7.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.7.0
tensorflow-cpu                2.7.0
tensorflow-datasets           4.4.0
tensorflow-estimator          2.7.0
tensorflow-io-gcs-filesystem  0.23.1
tensorflow-metadata           1.5.0
tensorflow-probability        0.15.0
termcolor                     1.1.0
threadpoolctl                 3.0.0
tifffile                      2022.4.8
timm                          0.4.12
toml                          0.10.2
toolz                         0.11.2
torch                         1.10.0
torchaudio                    0.10.0
torchvision                   0.11.1
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing_extensions             4.0.1
urllib3                       1.26.8
wcwidth                       0.2.5
Werkzeug                      2.0.2
wheel                         0.37.0
wrapt                         1.13.3
yacs                          0.1.6
zipp                          3.7.0
```

**Comment by Zoky-2020** [comment]
Try 'sh ./utils/rank_cylib/setup.sh'
